# 应用名称
spring:
  application:
    name: yuxs-config-server
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: admin

server:
  port: 8888

---
spring:
  profiles: dev
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
          add-label-locations: true
          default-label: @profile.env@
        git:
          #1.配置git仓库地址
          uri: https://github.com/yxs2100113/config.git
eureka:
  instance:
    #hostname: ${spring.cloud.client.ipAddress}
    prefer-ip-address: true
    #instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
    #过期时间配置:超过这个时间，EurekaServer没有接收到心跳，EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，
    #这个配置一般为服务刷新时间配置的三倍 默认90s
    lease-expiration-duration-in-seconds: 15
    #服务刷新时间配置，每隔这个时间会主动心跳一次 默认30s
    lease-renewal-interval-in-seconds: 5
  client:
    #eureka client刷新本地缓存时间 默认30s
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/